'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Namespace DateRangeFilterViaXpoDataSource


	Partial Public Class _Default

		''' <summary>
		''' form1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

		''' <summary>
		''' ASPxLabel1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxLabel1 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

		''' <summary>
		''' deStartDate control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected deStartDate As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

		''' <summary>
		''' ASPxLabel2 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxLabel2 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

		''' <summary>
		''' deEndDate control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected deEndDate As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

		''' <summary>
		''' ASPxGridView1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxGridView1 As Global.DevExpress.Web.ASPxGridView.ASPxGridView

		''' <summary>
		''' XpoDataSource1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected XpoDataSource1 As Global.DevExpress.Xpo.XpoDataSource
	End Class
End Namespace
